import { ReactNode } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Footer } from "./components/organisms/FooterSection/FooterSection";
import { Navbar } from "./components/organisms/Navbar/Navbar";
import "./styles/global.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Frontend Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
